### ISSUE TITLE
2022-4 not possible with current input fetcher

### ISSUE THREAD

**Issue by lyze237** [yugabe/Tidy.AdventOfCode#1]
Hey there!

Thanks for your great little library!

I've noticed that `rawInput` in a Day is trimmed, and since todays puzzle potentially starts with whitespaces it's not possible to solve:
![image](https://user-images.githubusercontent.com/11274700/205596365-7fc0ce18-61ed-4eef-a0a5-80e66afe0b5c.png)
![image](https://user-images.githubusercontent.com/11274700/205596442-c902ce5c-7771-46c4-b0fc-f0145531bbfd.png)

**Comment by yugabe** [comment]
Thank you very much for the report! I just saw this, will be pushing out a fix soon!

**Comment by yugabe** [comment]
Thank you @lyze237, 2.0.4 release is [out now on NuGet](https://www.nuget.org/packages/Tidy.AdventOfCode/2.0.4) with [fixes](https://github.com/yugabe/Tidy.AdventOfCode/blob/master/RELEASE_NOTES.md#204) including this one.
